# Generated by Django 5.0.4 on 2024-05-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectnotes_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectNotes',
        ),
    ]
